# Documentation:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

# Available software:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

# Useful info:
# https://stackoverflow.com/a/57549440/3977107

# Pandoc info:
# https://github.com/pandoc/dockerfiles#available-images
# https://github.com/leolabs/bachelor/blob/master/.github/workflows/main.yml
# https://github.com/maxheld83/pandoc/blob/master/.github/workflows/main.yml

name: CI Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        # see setup.py for supported versions
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        # should test sparingly across API breaking boundaries
        pandoc-version:
          # earliest supported pandoc version
          - 2.11.0.4
          - 2.11.1
          - 2.11.1.1
          - 2.11.2
          - 2.11.3
          - 2.11.3.1
          - 2.11.3.2
          - 2.11.4
          - 2.12
          - latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./panflute --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./panflute --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Download Pandoc
      run: |
        [[ ${{ matrix.pandoc-version }} == "latest" ]] && url="https://github.com/jgm/pandoc/releases/latest" || url="https://github.com/jgm/pandoc/releases/tag/${{ matrix.pandoc-version }}"
        downloadUrl="https://github.com$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')"
        wget --no-verbose "$downloadUrl"
        sudo dpkg -i "${downloadUrl##*/}"
        pandoc --version
    - name: Test with pytest
      run: pytest --color=yes
    - name: Test by running existing filters
      run: |
       mkdir -p $HOME/.local/share/pandoc/filters
       find ./examples/panflute ./docs/source/_static -iname '*.py' -exec cp {} $HOME/.local/share/pandoc/filters \;
       find . -iname '*.md' -print0 | xargs -0 -i -n1 -P4 bash -c 'pandoc -t native -F panflute -o $0.native $0' {}

# put filters in $DATADIR for panflute's autofilter
# running all available .md files through panflute
